FROM node:20-alpine
WORKDIR /app

# Copie de l'ensemble des manifestes de paquets pour résoudre l'espace de travail npm 🚀
COPY package*.json ./
COPY packages/commons/package*.json ./packages/commons/
COPY apps/server/package*.json ./apps/server/
COPY apps/client/package*.json ./apps/client/
COPY apps/extranet/package*.json ./apps/extranet/

RUN npm install

COPY . .

EXPOSE 4000